# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
version: 2.1

jobs:
  Build and lint:
    docker:
      - image: cimg/python:3.8.8-node
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Package
          command: npm run package
      - store_artifacts:
          path: ./web-ext-artifacts

workflows:
  ci:
    jobs:
      - Build and lint
